### ISSUE TITLE
Lecture 10 checklist

### ISSUE THREAD

**Issue by Pramell94** [OskarSundberg/TMUKGroup3#110]
Code covarage start : 3d9c244cf2ef42af5b97d36944bab9f43445e8be
This commit added the first WPF unit test to code covarage. Before the client showed 72% code covarage since it did not count the WPF part of Client. So should have started at around 20% code covarage if it did count WPF

Code covarage end : 6d7a38539f492448a9aabcc78d6d444c2f0a48e8

- [x] Test made by Simon #143 #140 
- [x] Test made by Samuel #130 
- [x] Test made by Gustav #141 #126
- [x] Test made by Ivo #153 
- [x] Test made by Oskar #128
