### ISSUE TITLE
Lecture 11 checklist

### ISSUE THREAD

**Issue by OskarSundberg** [OskarSundberg/TMUKGroup3#146]
# Server/Client
- [x] Add Whisper  f439eb2e81b4de3ad5541c5b4d20f90a0c208b99 306da815ced713beb28d8c5b99d0ad98d71205da
# WPF
- [x]  DarkMode 058d1d98d2fc9666356111018949645cef5c772b
- [x]  Autoscale 058d1d98d2fc9666356111018949645cef5c772b
