### ISSUE TITLE
checklist items for lecture 4

### ISSUE THREAD

**Issue by rudymatela** [OskarSundberg/TMUKGroup3#45]
Add tests to your project. Carry on with the project implementation.

Checklist:

* [x] Has a unit test.
* [x] Has several unit tests of different features and modules.
* [x] Tests are passing on the master/main branch.
* [x] README with instructions of how to run the unit tests.
* [x] README with instructions of how to generate code coverage information for your unit tests
* [x] README with instructions of how to run a linter for your project
* [x] If you are using assets found online as part of your project, please explicitly list these on the README.
