### ISSUE TITLE
Checklist for lecture 5 (CI)

### ISSUE THREAD

**Issue by rudymatela** [OskarSundberg/TMUKGroup3#70]
Add CI to your project.  Carry on with the project implementation.

* [x] Continuous Integration (CI) through GitHub Actions.
* [x] CI checks that your code compiles or parses.
* [x] CI checks that the unit tests are passing.
* [x] master/main is passing / green.
* [x] CI "badge" on the README
* [x] Optional items if you want to walk the extra mile 😁:
    - [x] (optional) CI produces code coverage information.
    - [x] (optional) CI performs lint checks.
